<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use InvalidArgumentException;

class BitikaService
{
    protected string $apiKey;
    protected string $baseUrl;

    public function __construct()
    {
        $this->apiKey = config('services.bitika.api_key');
        $this->baseUrl = config('services.bitika.base_url');

        if (!$this->apiKey) {
            throw new InvalidArgumentException("Bitika API key is not set in environment or config.");
        }
    }

    /**
     * Trigger an M-Pesa/Airtel Money STK Push to settle into a Lightning address or BOLT11 invoice.
     *
     * @param string $phone Phone number (e.g., "0712345678", "+254712345678", or "254712345678")
     * @param float|int|string $amount Amount in KES (Min: 10, Max: 10,000)
     * @param string $lightningAddress Lightning Address (e.g. "name@blink.sv"), BOLT11 invoice, or LNURL
     * @param string|null $idempotencyKey Optional UUID (autogenerated if omitted)
     * @return array
     */
    public function collect(
        string $phone,
        float|int|string $amount,
        string $lightningDestination,
        ?string $idempotencyKey = null
    ): array {
        $formattedPhone = $this->formatPhoneNumber($phone);
        $uuid = $idempotencyKey ?? (string) Str::uuid();

        // 1. Ensure amount is an integer or float, not a string
        $numericAmount = is_numeric($amount) ? (float) $amount : $amount;

        // 2. Detect if destination is a BOLT11 invoice or a Lightning Address
        $isBolt11 = Str::startsWith(strtolower($lightningDestination), ['lnbc', 'lntb', 'lnurl']);

        $payload = [
            'amount' => $numericAmount,
            'phone'  => $formattedPhone,
        ];

        if ($isBolt11) {
            // Many APIs use 'invoice' or 'paymentRequest' for BOLT11 strings
            $payload['invoice'] = $lightningDestination; 
        } else {
            $payload['lightningAddress'] = $lightningDestination;
        }

        Log::info("Initiating Bitika collect request", array_merge($payload, [
            'idempotencyKey' => $uuid,
        ]));

        $response = Http::withHeaders([
            'Authorization'   => "Bearer {$this->apiKey}",
            'Content-Type'    => 'application/json',
            'Idempotency-Key' => $uuid,
        ])->post("{$this->baseUrl}/xwift/collect", $payload);

        if ($response->failed()) {
            return [
                'success' => false,
                'status'  => $response->status(),
                'error'   => $response->json('message') ?? 'Bitika API request failed',
                'details' => $response->json(),
            ];
        }

        return [
            'success' => true,
            'data'    => $response->json(),
        ];
    }

    /**
     * Formats phone numbers into canonical format: 254XXXXXXXXX (no + or leading 0).
     */
    protected function formatPhoneNumber(string $phone): string
    {
        // Strip out non-numeric characters
        $phone = preg_replace('/\D/', '', $phone);

        // Convert 0712345678 or 0112345678 to 254712345678 / 254112345678
        if (Str::startsWith($phone, '0')) {
            $phone = '254' . substr($phone, 1);
        }

        // Validate 12-digit format starting with 254
        if (!preg_match('/^254\d{9}$/', $phone)) {
            throw new InvalidArgumentException("Invalid phone number format. Must be a valid 12-digit Kenyan phone number.");
        }

        return $phone;
    }
}