<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\URL;

class EmailVerificationController extends Controller
{
    /**
     * Verify the user's email address.
     *
     * This works even when the verification link is opened
     * on a different device/browser from the one used during signup.
     */
    public function verify(Request $request, int $id, string $hash): RedirectResponse
    {
        // Find the user from the ID contained in the signed URL.
        $user = User::findOrFail($id);

        // Verify that the URL was generated by our application
        // and has not been modified or expired.
        if (! URL::hasValidSignature($request)) {
            abort(403, 'This verification link is invalid or has expired.');
        }

        // Verify that the hash in the URL actually belongs
        // to this user's email address.
        if (! hash_equals(
            sha1($user->getEmailForVerification()),
            $hash
        )) {
            abort(403, 'This verification link is invalid.');
        }

        // Mark the email as verified if it hasn't already been verified.
        if (! $user->hasVerifiedEmail()) {
            $user->markEmailAsVerified();
        }

        // Log the user in on the device where they clicked the link.
        Auth::login($user);

        // Prevent session fixation.
        $request->session()->regenerate();

        // Send them to your success page.
        return redirect()->route('verification.success');
    }

    
}